### PR TITLE
fixed some clippy warnings

### PR DESCRIPTION
**Pull request by llogiq**

### CODE REVIEW

**Comment by phaazon** [comment]
Hm, how is that possible I’m told about the `clippy` set of lints only now! That rocks! I’ll use them from now on. Thank you.

**Comment by llogiq** [comment]
You're welcome. Note that you'll need a current nightly to run clippy.

**Comment by phaazon** [comment]
I know, I’ve already fixed some other warnings thanks to that. Thanks ;)

**Comment by phaazon** [comment]
I know, I’ve already fixed some other warnings thanks to that. Thanks ;)

**Comment by phaazon** [comment]
I know, I’ve already fixed some other warnings thanks to that. Thanks ;)

**Pull request merged**
